return {
  ensure_installed = {
    "bash",
    "c",
    "cpp",
    "css",
    "dart",
    "go",
    "html",
    "java",
    "javascript",
    "json",
    "just",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "python",
    "rust",
    "ruby",
    "sql",
    "toml",
    "tsx",
    "typescript",
    "yaml",
    "zig",
  },

  sync_install = false,
  auto_install = true,

  highlight = {
    enable = true,
    use_languagetree = true,
  },

  indent = { enable = true },
  endwise = { enable = true },
  autotag = {
    enable = true,
    enable_rename = true,
    enable_close = true,
    enable_close_on_slash = true,
  },
}
